name: Release AgentKit Core to NPM

on:
  workflow_dispatch:

jobs:
  deploy-agentkit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
      # Install dependencies in parent directory first
      - run: npm ci
      # Then install, build and publish in working directory
      - name: Install, build and publish agentkit
        working-directory: ./cdp-agentkit-core
        run: |
          npm ci
          npm run build
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
